// sample.ts — каталог KAGE из прототипа дизайна.
// Реальные публичные тайтлы; постеры — стилизованные SVG-плейсхолдеры по palette.
// TODO(shikimori): заменить на данные GraphQL, сохранив форму Anime.

import type { Anime, Episode, Rail } from "./types";

export const ANIME: Anime[] = [
  {
    id: "frieren",
    title: "Frieren: Beyond Journey’s End",
    titleRu: "Фрирен: За пределами путешествия",
    titleJp: "葬送のフリーレン",
    year: 2023,
    eps: 28,
    rating: 9.3,
    age: "12+",
    genres: ["Фэнтези", "Драма", "Приключения"],
    studio: "Madhouse",
    tagline: "Тысяча лет. Один взгляд назад.",
    synopsis:
      "Эльфийская волшебница Фрирен пережила своих спутников и теперь странствует, чтобы понять, что значит быть человеком.",
    palette: ["#1a3a4f", "#5fbac0", "#f0e4c3"],
  },
  {
    id: "jjk",
    title: "Jujutsu Kaisen",
    titleRu: "Магическая битва",
    titleJp: "呪術廻戦",
    year: 2023,
    eps: 47,
    rating: 8.7,
    age: "16+",
    genres: ["Сёнен", "Сверхъестественное", "Экшен"],
    studio: "MAPPA",
    tagline: "Проклятие силы — это сила.",
    synopsis:
      "Юдзи Итадори становится сосудом для древнего проклятого духа и попадает в школу экзорцистов.",
    palette: ["#1b1b2e", "#5b2a86", "#ff4d6d"],
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    titleRu: "Истребитель демонов",
    titleJp: "鬼滅の刃",
    year: 2024,
    eps: 55,
    rating: 8.9,
    age: "16+",
    genres: ["Сёнен", "Экшен", "Историческое"],
    studio: "ufotable",
    tagline: "Клинок, рассекающий ночь.",
    synopsis:
      "Тандзиро Камадо вступает в корпус истребителей демонов, чтобы вернуть сестре человеческий облик.",
    palette: ["#0e2e2a", "#1f8a5b", "#f6d365"],
  },
  {
    id: "aot",
    title: "Attack on Titan",
    titleRu: "Атака титанов",
    titleJp: "進撃の巨人",
    year: 2023,
    eps: 89,
    rating: 9.1,
    age: "18+",
    genres: ["Экшен", "Драма", "Постапокалипсис"],
    studio: "MAPPA",
    tagline: "Стены падают. Мир — тоже.",
    synopsis:
      "Эрен Йегер ведёт войну за свободу человечества, заключённого внутри стен от гигантских титанов.",
    palette: ["#231910", "#a23e1a", "#e8c89c"],
  },
  {
    id: "spyfamily",
    title: "Spy × Family",
    titleRu: "Семья шпиона",
    titleJp: "スパイファミリー",
    year: 2024,
    eps: 37,
    rating: 8.6,
    age: "12+",
    genres: ["Комедия", "Экшен", "Семейное"],
    studio: "WIT × CloverWorks",
    tagline: "Лучшая семья на Земле — фальшивая.",
    synopsis:
      "Шпион, телепат и убийца притворяются обычной семьёй, чтобы предотвратить международный кризис.",
    palette: ["#2c1f3f", "#e85b8a", "#fce38a"],
  },
  {
    id: "chainsaw",
    title: "Chainsaw Man",
    titleRu: "Человек-бензопила",
    titleJp: "チェンソーマン",
    year: 2023,
    eps: 12,
    rating: 8.4,
    age: "18+",
    genres: ["Экшен", "Сверхъестественное", "Хоррор"],
    studio: "MAPPA",
    tagline: "Простые мечты, грязные руки.",
    synopsis:
      "Бедный охотник на демонов Дэндзи сливается с дьяволом-питомцем и становится Человеком-бензопилой.",
    palette: ["#1a0e0e", "#ff3b30", "#f5a623"],
  },
  {
    id: "vinland",
    title: "Vinland Saga",
    titleRu: "Сага о Винланде",
    titleJp: "ヴィンランド・サガ",
    year: 2023,
    eps: 48,
    rating: 9.0,
    age: "18+",
    genres: ["Драма", "Историческое", "Приключения"],
    studio: "MAPPA",
    tagline: "Где-то на западе есть земля без войны.",
    synopsis:
      "Молодой викинг Торфинн мстит за отца, проходя путь от воина до пахаря.",
    palette: ["#0d1b2a", "#415a77", "#d4cba0"],
  },
  {
    id: "oshinoko",
    title: "Oshi no Ko",
    titleRu: "Дитя моей звезды",
    titleJp: "推しの子",
    year: 2024,
    eps: 24,
    rating: 8.8,
    age: "16+",
    genres: ["Драма", "Мистика", "Шоубиз"],
    studio: "Doga Kobo",
    tagline: "Звёзды — лжецы по контракту.",
    synopsis:
      "Врач перерождается в сына любимой айдол-певицы и попадает в тёмный мир японского шоу-бизнеса.",
    palette: ["#1d0a2e", "#ff4ecd", "#7c4dff"],
  },
  {
    id: "mob",
    title: "Mob Psycho 100",
    titleRu: "Моб Психо 100",
    titleJp: "モブサイコ100",
    year: 2022,
    eps: 37,
    rating: 8.9,
    age: "12+",
    genres: ["Сверхъестественное", "Комедия", "Драма"],
    studio: "Bones",
    tagline: "100% обычный школьник.",
    synopsis:
      "Школьник с огромной экстрасенсорной силой пытается просто прожить нормальную жизнь.",
    palette: ["#102a3a", "#00d4d4", "#ff6f3c"],
  },
  {
    id: "bocchi",
    title: "Bocchi the Rock!",
    titleRu: "Одинокий рокер!",
    titleJp: "ぼっち・ざ・ろっく！",
    year: 2022,
    eps: 12,
    rating: 8.7,
    age: "12+",
    genres: ["Комедия", "Музыка", "Школа"],
    studio: "CloverWorks",
    tagline: "Гитара громче, чем тревога.",
    synopsis:
      "Социофобка Хитори Гото мечтает стать рок-звездой, не выходя из шкафа в прямом смысле.",
    palette: ["#2a1b3d", "#ff7eb3", "#ffd166"],
  },
  {
    id: "dandadan",
    title: "Dandadan",
    titleRu: "Дандадан",
    titleJp: "ダンダダン",
    year: 2024,
    eps: 12,
    rating: 8.6,
    age: "16+",
    genres: ["Сверхъестественное", "Комедия", "Экшен"],
    studio: "Science SARU",
    tagline: "Призраки против пришельцев. Подростки посередине.",
    synopsis:
      "Двое школьников оказались втянуты в войну духов и инопланетян после совершенно глупого спора.",
    palette: ["#0f0628", "#ff007a", "#00ffd0"],
  },
  {
    id: "cyberpunk",
    title: "Cyberpunk: Edgerunners",
    titleRu: "Киберпанк: Бегущие по краю",
    titleJp: "サイバーパンク エッジランナーズ",
    year: 2022,
    eps: 10,
    rating: 8.6,
    age: "18+",
    genres: ["Сай-фай", "Экшен", "Драма"],
    studio: "Trigger",
    tagline: "В Найт-Сити каждый — товар.",
    synopsis:
      "Уличный пацан Дэвид Мартинес становится наёмником-эджраннером в неоновом аду Найт-Сити.",
    palette: ["#0a0a1f", "#ffe600", "#ff007a"],
  },
  {
    id: "violet",
    title: "Violet Evergarden",
    titleRu: "Вайолет Эвергарден",
    titleJp: "ヴァイオレット・エヴァーガーデン",
    year: 2018,
    eps: 13,
    rating: 8.9,
    age: "12+",
    genres: ["Драма", "Романтика"],
    studio: "Kyoto Animation",
    tagline: "Что значит «я люблю тебя»?",
    synopsis:
      "Бывший боевой автомат Вайолет учится понимать чувства, работая ауто-памятной куклой.",
    palette: ["#1a2a44", "#5ba8d8", "#f8e6ce"],
  },
  {
    id: "abyss",
    title: "Made in Abyss",
    titleRu: "Созданный в бездне",
    titleJp: "メイドインアビス",
    year: 2022,
    eps: 25,
    rating: 8.8,
    age: "16+",
    genres: ["Фэнтези", "Приключения", "Драма"],
    studio: "Kinema Citrus",
    tagline: "Назад дороги нет.",
    synopsis:
      "Девочка Рико спускается в бездонную яму на поиски матери, не зная, что её ждёт внизу.",
    palette: ["#1a1308", "#c97b3a", "#f4d58d"],
  },
  {
    id: "apothecary",
    title: "The Apothecary Diaries",
    titleRu: "Монологи фармацевта",
    titleJp: "薬屋のひとりごと",
    year: 2024,
    eps: 24,
    rating: 8.9,
    age: "12+",
    genres: ["Мистика", "Драма", "Историческое"],
    studio: "OLM × TOHO",
    tagline: "Яд знает имя каждого.",
    synopsis:
      "Юная травница Маомао распутывает интриги императорского дворца — лучше, чем её собственная жизнь.",
    palette: ["#2a1418", "#d44267", "#f6c5a5"],
  },
  {
    id: "solo",
    title: "Solo Leveling",
    titleRu: "Поднятие уровня в одиночку",
    titleJp: "俺だけレベルアップな件",
    year: 2024,
    eps: 25,
    rating: 8.4,
    age: "16+",
    genres: ["Экшен", "Фэнтези"],
    studio: "A-1 Pictures",
    tagline: "Арайз.",
    synopsis:
      "Слабейший охотник Сон Джину получает уникальную систему прокачки и становится самой мощной силой в мире.",
    palette: ["#0c0c2a", "#7c3aed", "#22d3ee"],
  },
  {
    id: "bleach",
    title: "Bleach: Thousand-Year Blood War",
    titleRu: "Блич: Тысячелетняя кровавая война",
    titleJp: "BLEACH 千年血戦篇",
    year: 2024,
    eps: 26,
    rating: 9.0,
    age: "16+",
    genres: ["Сёнен", "Экшен", "Сверхъестественное"],
    studio: "Pierrot",
    tagline: "Последний рассвет Готея.",
    synopsis:
      "Ичиго Куросаки и Готей 13 встречают древнего врага синигами — квинси Яхвач.",
    palette: ["#0a0a14", "#cc0033", "#e6e6e6"],
  },
  {
    id: "onepiece",
    title: "One Piece",
    titleRu: "Ван-Пис",
    titleJp: "ワンピース",
    year: 2024,
    eps: 1118,
    rating: 9.0,
    age: "12+",
    genres: ["Сёнен", "Приключения", "Экшен"],
    studio: "Toei Animation",
    tagline: "Король пиратов — это я.",
    synopsis:
      "Луффи и его команда плывут в Гранд-Лайн в поисках легендарного сокровища Ван-Пис.",
    palette: ["#0f3460", "#e94560", "#f5d042"],
  },
];

export const ANIME_BY_ID: Record<string, Anime> = Object.fromEntries(
  ANIME.map((a) => [a.id, a]),
);

export const RAILS: Rail[] = [
  {
    id: "continue",
    title: "Продолжить просмотр",
    subtitle: "Где вы остановились",
    ids: ["frieren", "jjk", "apothecary", "dandadan"],
    progress: [0.34, 0.71, 0.12, 0.88],
  },
  {
    id: "trending",
    title: "В тренде на этой неделе",
    subtitle: "Топ 10",
    ids: [
      "solo",
      "dandadan",
      "frieren",
      "apothecary",
      "jjk",
      "oshinoko",
      "spyfamily",
      "demon-slayer",
      "bleach",
      "chainsaw",
    ],
  },
  {
    id: "new",
    title: "Новые серии",
    subtitle: "Свежие эпизоды",
    ids: ["frieren", "apothecary", "dandadan", "solo", "bleach", "demon-slayer"],
  },
  {
    id: "drama",
    title: "Душу наизнанку",
    subtitle: "Лучшая драма",
    ids: ["violet", "vinland", "oshinoko", "aot", "mob"],
  },
  {
    id: "classics",
    title: "Классика, которую стоит увидеть",
    subtitle: "8.7+ рейтинг",
    ids: ["cyberpunk", "violet", "abyss", "mob", "bocchi"],
  },
  {
    id: "studio",
    title: "От студии MAPPA",
    subtitle: "Подборка студии",
    ids: ["jjk", "aot", "chainsaw", "vinland"],
  },
];

const EPISODE_TITLES: Record<string, string[]> = {
  frieren: [
    "Путешествие окончено",
    "Тысячелетний друг",
    "Аура убийца",
    "Город магов",
    "Зеркальный лотос",
    "Кубинский монах",
    "Имя для меча",
    "Серый рыцарь",
    "Граница демонов",
    "Похороны мага",
    "Тень Хидака",
    "Завет учителя",
  ],
  jjk: [
    "Юдзи Итадори",
    "Юная жизнь",
    "Заря",
    "Проклятое дитя",
    "Куросирокудзи",
    "Шкаф",
    "Восстание",
    "Гэто Сугуру",
    "Шибуя",
    "Сюкуна",
    "Жил-был некто",
    "Истинная форма",
  ],
};

const FALLBACK_TITLES = [
  "Тень в ночи",
  "Огонь и пепел",
  "Имя на ветру",
  "Граница миров",
  "Тихий зов",
  "Последний клинок",
  "Эхо памяти",
  "Свет из бездны",
  "Чёрный прилив",
  "Гнев небес",
  "Финал",
];

export function getEpisodes(id: string, count = 12): Episode[] {
  const titles = EPISODE_TITLES[id];
  const palette = ANIME_BY_ID[id]?.palette ?? ["#222", "#444", "#666"];
  return Array.from({ length: count }, (_, i) => ({
    num: i + 1,
    title: titles?.[i] ?? FALLBACK_TITLES[i % FALLBACK_TITLES.length],
    duration: 24,
    thumb: palette,
  }));
}
